stages:
  - setup
  - lint

setup:
  stage: setup
  script:
    - npm i
  artifacts:
    paths:
      - node_modules/
      - vendor/
    expire_in: 1 minutes

lint:
  stage: lint
  script:
    - grunt lint
  dependencies:
    - setup
  artifacts:
    when: on_failure
    paths:
      - phpcbf.diff
    expire_in: 200 minutes
